server:
  service:
    type: LoadBalancer
  extraArgs:
    - --insecure
  resources:
    requests:
      cpu: 200m
      memory: 200Mi
    limits:
      cpu: 250m
      memory: 400Mi

controller:
  replicas: 1
  resources:
    requests:
      cpu: 200m
      memory: 200Mi
    limits:
      cpu: 250m
      memory: 400Mi

repoServer:
  replicas: 1
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi
  volumeMounts:
    - name: tmp
      mountPath: /tmp
  volumes:
    - name: tmp
      emptyDir: {}

redis:
  enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 100m
      memory: 200Mi

applicationSet:
  resources:
    requests:
      cpu: 200m
      memory: 100Mi
    limits:
      cpu: 250m
      memory: 200Mi
