stages:
  - train

train-model:
  stage: train
  image: amazon/aws-cli:2.15.0
  variables:
    AWS_ACCESS_KEY_ID: "$AWS_ACCESS_KEY_ID"
    AWS_SECRET_ACCESS_KEY: "$AWS_SECRET_ACCESS_KEY"
    AWS_DEFAULT_REGION: "$AWS_REGION"
    STATE_MACHINE_ARN: "$STATE_MACHINE_ARN"
  script:
    - echo "AWS CLI version:"
    - aws --version
    - echo "Starting Step Function execution..."
    - aws stepfunctions start-execution \
        --state-machine-arn "$STATE_MACHINE_ARN" \
        --name "train-$(date +%s)" \
        --input '{"source":"gitlab-ci","commit":"'$CI_COMMIT_SHORT_SHA'"}'
  only:
    - branches
